version: '3.7'

services:
  db-host:
    image: mysql:5.7
    # restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test_db_env
      MYSQL_DATABASE: dearcare
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command: # 명령어 실행
      - --explicit_defaults_for_timestamp=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: scrape-db
    ports:
    - 3307:3306

volumes:
  mysql-data: